### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by ghost** [anabranch/udemy_data_analysis_python#3]
In file: 4 - pandas Basics/4-3 pandas Series NaNs, Reindexing, filling, mutating and copies, basic mapping.ipynb

It looks like cell #26:

``` python
s2.index = [range(3,8)]
s2
```

Should be:

``` python
s2.index = list(range(3,8))
s2
```

EDIT: or just

``` python
s2.index = range(3, 8)
s2
```

**Comment by bllchmbrs** [comment]
Thanks Kevin I'll check this out today!

**Comment by bllchmbrs** [comment]
all fixed up, thanks Kevin!
